/*
 * This file is generated by jOOQ.
 */
package dev.kinman.app.jooq;


import dev.kinman.app.jooq.tables.Databasechangeloglock;
import dev.kinman.app.jooq.tables.WeatherStations;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.weather_stations</code>.
     */
    public static final WeatherStations WEATHER_STATIONS = WeatherStations.WEATHER_STATIONS;
}
